export const SatilikYat = [
     {
          id: 1,
          tip: 'satilik',
          title: "Azura 42",
          ilanTarihi: "31.12.2023",
          ilanNo: "1214161820",
          tur: "Motor yat",
          marka: "Azura",
          model: "A42 Special",
          uretimYili: 2018,
          boyMetre: 27,
          enMetre: 6,
          govdeMalzemesi: "Fiberglass",
          kameraSayisi: 5,
          yatakSayisi: 2,
          motorAdedi: 2,
          motorGucuHP: 1950,
          yakitTipi: "Dizel",
          kimden: "Sahibinden",
          durumu: "İkinci El",
          bandira: "Diğer",
          bulunduguYer: "Denizde",
          fiyat: '25.450.000',
          currency: "EUR",
          ozet: "Konforlu haftasonu gezileri ve kiralama için uygun, iyi bakımlı motor yat.",
          ozellikler: [
               "Banyo, WC",
               "Yatak Odası",
               "Mutfak",
               "Klima",
               "Navigasyon Paketi",
               "Çift motor sistemi"
          ],
          images: [
               require("../../assets/icons/fake-yachts/SatilikYat1_photo1.png"),
               require("../../assets/icons/fake-yachts/SatilikYat1_photo2.png"),
               require("../../assets/icons/fake-yachts/SatilikYat1_photo3.png"),
               require("../../assets/icons/fake-yachts/SatilikYat1_photo4.png"),
               require("../../assets/icons/fake-yachts/SatilikYat1_photo5.png"),
          ],
     },

     {
          id: 2,
          tip: 'satilik',
          title: "Mariner 36 Classic",
          ilanTarihi: "15.11.2023",
          ilanNo: "1214161821",
          tur: "Motor yat",
          marka: "Mariner",
          model: "36 Classic",
          uretimYili: 2016,
          boyMetre: 24,
          enMetre: 5.2,
          govdeMalzemesi: "Fiberglass",
          kameraSayisi: 4,
          yatakSayisi: 3,
          motorAdedi: 2,
          motorGucuHP: 1400,
          yakitTipi: "Dizel",
          kimden: "Sahibinden",
          durumu: "İkinci El",
          bandira: "Türkiye",
          bulunduguYer: "Bodrum, Muğla",
          fiyat: '12.980.000',
          currency: "EUR",
          ozet: "Aile kullanımına uygun, geniş salon ve iyi depo kapasiteli teknedir.",
          ozellikler: [
               "Mutfak (galley)",
               "WC",
               "Duş",
               "Güneşlenme alanı",
               "Stereo",
          ],
          images: [
               require("../../assets/icons/fake-yachts/SatilikYat2_photo1.png"),
               require("../../assets/icons/fake-yachts/SatilikYat2_photo2.png"),
               require("../../assets/icons/fake-yachts/SatilikYat2_photo3.png"),
               require("../../assets/icons/fake-yachts/SatilikYat2_photo4.png"),
               require("../../assets/icons/fake-yachts/SatilikYat2_photo5.png"),
          ],
     },

     {
          id: 3,
          tip: 'satilik',
          title: "Oceanic 55 Explorer",
          ilanTarihi: "02.08.2024",
          ilanNo: "1214161822",
          tur: "Motoryat / Lüks",
          marka: "Oceanic",
          model: "55 Explorer",
          uretimYili: 2020,
          boyMetre: 30,
          enMetre: 7.5,
          govdeMalzemesi: "Alüminyum",
          kameraSayisi: 6,
          yatakSayisi: 5,
          motorAdedi: 3,
          motorGucuHP: 3200,
          yakitTipi: "Dizel",
          kimden: "Broker",
          durumu: "İkinci El",
          bandira: "Cayman",
          bulunduguYer: "İstanbul",
          fiyat: '13.850.000',
          currency: "EUR",
          ozet: "Uzun seyirler için donanımlı, geniş depolama ve konforlu kabinler.",
          ozellikler: [
               "Geniş VIP kamarası",
               "Tam donanımlı mutfak",
               "İklimlendirme",
               "Jeneratör",
               "Radar ve GPS",
          ],
          images: [
               require("../../assets/icons/fake-yachts/SatilikYat3_photo1.png"),
               require("../../assets/icons/fake-yachts/SatilikYat3_photo2.png"),
               require("../../assets/icons/fake-yachts/SatilikYat3_photo3.png"),
               require("../../assets/icons/fake-yachts/SatilikYat3_photo4.png"),
               require("../../assets/icons/fake-yachts/SatilikYat3_photo5.png"),
          ],
     },

     {
          id: 4,
          tip: 'satilik',
          title: "Prima 28 Daycruiser",
          ilanTarihi: "10.06.2022",
          ilanNo: "1214161823",
          tur: "Motor yat",
          marka: "Prima",
          model: "28 Daycruiser",
          uretimYili: 2014,
          boyMetre: 18,
          enMetre: 4.8,
          govdeMalzemesi: "Fiberglass",
          kameraSayisi: 2,
          yatakSayisi: 2,
          motorAdedi: 1,
          motorGucuHP: 700,
          yakitTipi: "Benzin",
          kimden: "Sahibinden",
          durumu: "İkinci El",
          bandira: "Türkiye",
          bulunduguYer: "Kuşadası, Aydın",
          fiyat: '43.220.000',
          currency: "EUR",
          ozet: "Haftasonu gezi tekneleri için ideal; ekonomik işletme maliyeti.",
          ozellikler: [
               "WC",
               "Mutfak",
               "Küçük güneşlenme alanı",
          ],
          images: [
               require("../../assets/icons/fake-yachts/SatilikYat4_photo1.png"),
               require("../../assets/icons/fake-yachts/SatilikYat4_photo2.png"),
               require("../../assets/icons/fake-yachts/SatilikYat4_photo3.png"),
               require("../../assets/icons/fake-yachts/SatilikYat4_photo4.png"),
               require("../../assets/icons/fake-yachts/SatilikYat4_photo4.png"),
          ],
     },

     {
          id: 5,
          tip: 'satilik',
          title: "Heritage Classic 50",
          ilanTarihi: "05.01.2021",
          ilanNo: "1214161824",
          tur: "Klasik motor yat",
          marka: "Heritage",
          model: "Classic 50",
          uretimYili: 2005,
          boyMetre: 27,
          enMetre: 6.3,
          govdeMalzemesi: "Ahşap/Fiberglass",
          kameraSayisi: 3,
          yatakSayisi: 4,
          motorAdedi: 2,
          motorGucuHP: 1200,
          yakitTipi: "Dizel",
          kimden: "Broker",
          durumu: "Restorasyona uygun",
          bandira: "Diğer",
          bulunduguYer: "Çanakkale",
          fiyat: '6.780.000',
          currency: "EUR",
          ozet: "Klasik hatlara sahip, restorasyon veya butik otel/proje olarak değerlendirilebilir.",
          ozellikler: [
               "Klasik iç döşeme",
               "Geniş güverte",
               "Yedek parçalar mevcut",
          ],
          images: [
               require("../../assets/icons/fake-yachts/SatilikYat5_photo1.png"),
               require("../../assets/icons/fake-yachts/SatilikYat5_photo2.png"),
               require("../../assets/icons/fake-yachts/SatilikYat5_photo3.png"),
               require("../../assets/icons/fake-yachts/SatilikYat5_photo4.png"),
               require("../../assets/icons/fake-yachts/SatilikYat5_photo5.png"),
          ],
     },
];